"""Session Attendees

Revision ID: 2088f98b5689
Revises: 3977e5a07b0d
Create Date: 2023-11-08 23:10:08.401242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2088f98b5689'
down_revision = '3977e5a07b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_attendees',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'student_id')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Schedule_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('Schedule_name')

    op.drop_table('module_attendees')
    # ### end Alembic commands ###
