"""Added phone_number to student and tm

Revision ID: 3977e5a07b0d
Revises: e0572262f7a5
Create Date: 2023-11-06 18:02:37.663806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3977e5a07b0d'
down_revision = 'e0572262f7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    with op.batch_alter_table('technical_mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_mentors', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
