"""Updated schema

Revision ID: bcc228aec7ef
Revises: 2088f98b5689
Create Date: 2023-11-09 10:53:13.353033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc228aec7ef'
down_revision = '2088f98b5689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')
        batch_op.drop_column('Schedule_name')
        batch_op.drop_column('date')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('date')
        batch_op.drop_column('location')
        batch_op.drop_column('invite_link')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('Schedule_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
