"""email-confirmation

Revision ID: e0572262f7a5
Revises: 5f9e5b4dff45
Create Date: 2023-11-03 19:52:04.784637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0572262f7a5'
down_revision = '5f9e5b4dff45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
